core/urls.py
from django.urls import path

from core.views import index, login
from core.views import user
from core.views import worker
from core.views import reports
from core.views import directions
from core.views import log
from core.views import rest

app_name = 'core'

urlpatterns = [
    path('', index.Index.as_view(), name='index'),

    path('user/', user.Search.as_view(), name='user'),
    path('user/add/', user.Edit.as_view(), name='user_add'),
    path('user/<int:pk>/', user.Edit.as_view(), name='user_edit'),
    path('user/<int:pk>/delete/', user.Delete.as_view(), name='user_delete'),

    path('workers/', worker.Search.as_view(), name='workers'),
    path('reports/workers_done_report/', reports.WorkersDoneReport.as_view(), name='workers_done_report'),

    path('log/', log.Log.as_view(), name='log'),

    path('directions/', directions.Search.as_view(), name='direction_list'),
    path('directions/add/', directions.Edit.as_view(), name='direction_add'),
    path('directions/<int:number>/', directions.Edit.as_view(), name='direction_edit'),
    path('directions/<int:number>/delete/', directions.Delete.as_view(), name='direction_delete'),
    path('directions/<int:number>/print/', directions.Print.as_view(), name='direction_print'),

    path('rest/orgs/', rest.Orgs.as_view(), name='rest_orgs'),
    path('rest/workers/', rest.Workers.as_view(), name='rest_workers'),
    path('rest/documents/choices/', rest.DocumentsChoices.as_view(), name='rest_documents_choices'),
    path('rest/documents/print/', rest.DocumentPrint.as_view(), name='rest_documents_print'),
    path('rest/worker_documents/', rest.WorkerDocuments.as_view(), name='rest_worker_documents'),
    path('rest/law_items/', rest.LawItems.as_view(), name='rest_law_items'),
    path('rest/generate_password/', rest.GeneratePasswordView.as_view(), name='rest_generate_password'),

    path('password_change_required/', login.PasswordChangeRequired.as_view(), name='password_change_required'),
    path('password_forgot/', login.PasswordForgot.as_view(), name='password_forgot'),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, PasswordChangeView, logout_then_login
from django.views.generic import TemplateView

import core.urls
import help.urls
import background_tasks.urls
from core.views.login import Login

urlpatterns = [
    path('', include(core.urls, namespace='core')),
    path('help/', include(help.urls, namespace='help')),
    path('background_tasks/', include(background_tasks.urls, namespace='background_tasks')),
    path('admin/', admin.site.urls),

    path('login/', Login.as_view(), name='login'),
    path('logout/', logout_then_login, {'login_url': '/login/?next=/'}, name='logout'),

    path('password_change/', PasswordChangeView.as_view(template_name='core/password_change.html',
                                                        success_url='/logout/'), name='password_change'),
]

handler403 = 'core.views.response_forbidden_handler'
handler404 = 'core.views.response_not_found_error_handler'
handler500 = 'core.views.response_server_error_handler'

if settings.DEBUG:
    urlpatterns += static('node_modules', document_root=settings.BASE_DIR + '/node_modules')
    urlpatterns += static('media', document_root=settings.MEDIA_ROOT)

    urlpatterns = [
        # для отладки страниц ошибок
        path('403/', TemplateView.as_view(template_name='core/errors/403.html')),
        path('404/', TemplateView.as_view(template_name='core/errors/404.html')),
        path('500/', TemplateView.as_view(template_name='core/errors/500.html')),
    ] + urlpatterns

core/generic/views.py
import sys
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect

from django.views.generic import (
    ListView as DjangoListView,
    UpdateView as DjangoUpdateView,
    DeleteView as DjangoDeleteView,
)

from core.generic import mixins


class ListView(mixins.ExcelMixin, mixins.BreadcrumbsMixin, mixins.TitleMixin, DjangoListView):
    DEFAULT_PAGINATE_BY = 50

    def get_paginate_by(self, queryset=None):
        paginate_by = self.request.session.get(f'per_page-{self.request.path}',
                                               self.paginate_by or self.DEFAULT_PAGINATE_BY)
        per_page = self.request.GET.get('per_page')
        if per_page:
            self.request.session[f'per_page-{self.request.path}'] = per_page
            paginate_by = per_page

        return paginate_by if paginate_by != 'all' else sys.maxsize

    def get_page_numbers(self, queryset=None):

        if queryset is None:
            queryset = self.get_queryset()

        numbers = []
        if queryset:
            page = int(self.request.GET.get('page', 1))
            per_page = self.get_paginate_by(queryset)

            pag = self.get_paginator(queryset, per_page or len(queryset))
            all_numbers = list(pag.page_range)

            start = page - 4 if page - 4 > 1 else 0
            end = page + 3
            numbers = all_numbers[start:end]

        has_left = False
        has_right = False
        if numbers:
            has_left = numbers[0] != all_numbers[0]
            has_right = numbers[-1] != all_numbers[-1]

        return has_left, numbers, has_right

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        queryset = None
        if hasattr(self, 'object_list'):
            queryset = self.object_list

        has_left, numbers, has_right = self.get_page_numbers(queryset=queryset)
        context['page_has_left'] = has_left
        context['page_numbers'] = numbers
        context['page_has_right'] = has_right
        return context

    def get_filter_params(self):
        form = self.get_form()
        if form.is_valid():
            filter_params = form.cleaned_data
        else:
            filter_params = self.get_initial()

        return filter_params

    def get_queryset(self):
        queryset = self.filter_class(
            data=self.get_filter_params(),
            request=self.request,
        ).qs
        return queryset.distinct()


class EditView(mixins.BreadcrumbsMixin, mixins.TitleMixin, mixins.FormMixin, DjangoUpdateView):
    object = None

    def get_object(self):
        object_pk = self.kwargs.get(self.pk_url_kwarg)
        if object_pk:
            self.object = get_object_or_404(self.model, pk=object_pk)

        return self.object

    def get_title(self):
        if obj := self.get_object():
            return str(obj)
        else:
            return 'Создание'

    def form_valid(self, form):
        form.save()
        return redirect(self.get_success_url())


class DeleteView(mixins.BreadcrumbsMixin, mixins.TitleMixin, DjangoDeleteView):
    object = None
    delete_message = None
    template_name = 'core/base_delete.html'

    def get_delete_message(self):
        return self.delete_message or str(self.object)

    def get_object(self, queryset=None):
        if not self.object:
            self.object = super().get_object(queryset=queryset)

        return self.object

    def get_title(self):
        return f'Удаление "{self.get_object()}"'

    def delete(self, *args, **kwargs):
        response = super().delete(*args, **kwargs)

        if self.request.is_ajax():
            response = HttpResponse('ok')

        return response

core/views/admin.py
from django.conf import settings
from django.views.generic import TemplateView
from django.contrib.auth.mixins import PermissionRequiredMixin


class Management(PermissionRequiredMixin, TemplateView):
    template_name = 'core/admin.html'
    permission_required = 'core.view_management'

core/views/directions.py
import dataclasses
import datetime
import json
import logging
import os
import tempfile

from core.excel.directions import DirectionsExcel
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.core.files import File
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.views.generic.base import View
import sw_logger.consts
from docx.shared import Mm

from mis.direction import Direction
from mis.org import Org
from mis.service_client import Mis
from core.datatools.report import get_report_period

import core.generic.mixins
import core.generic.views
import core.datatools.barcode

from core import forms, models


logger = logging.getLogger('db')


class Search(PermissionRequiredMixin, core.generic.mixins.FormMixin, core.generic.mixins.RestListMixin,
             core.generic.views.ListView):
    form_class = forms.DirectionSearch
    title = 'Направления'
    permission_required = 'core.view_direction'
    paginate_by = 50
    excel_workbook_maker = DirectionsExcel
    template_name = settings.TEMPLATES_DICT.get("direction_list")
    mis_request_path = Mis.DIRECTIONS_LIST_URL

    def get_workbook_maker_kwargs(self, **kwargs):
        kwargs = super().get_workbook_maker_kwargs(**kwargs)

        user_orgs = self.request.user.core.get_orgs()
        kwargs['show_orgs'] = False if user_orgs and len(user_orgs) < 2 else True
        kwargs['mis_request_path'] = self.mis_request_path
        kwargs['filter_params'] = self.get_filter_params()
        return kwargs

    def get_excel_title(self):
        title = self.get_title()

        form = self.get_form()
        if form.is_valid():
            title += get_report_period(
                date_from=form.cleaned_data.get('date_from'),
                date_to=form.cleaned_data.get('date_to')
            )

            if orgs := form.cleaned_data.get('orgs'):
                title += f'. Организации: {", ".join(str(org) for org in orgs)}'

        return title

    def get_initial(self):
        initial = super().get_initial()
        initial['date_from'] = datetime.date.today()
        return initial

    def get_filter_params(self):
        form = self.get_form()
        if form.is_valid():
            filter_params = form.cleaned_data
        else:
            filter_params = self.get_initial()

        return filter_params

    def process_response_results(self, objects):
        return [Direction.dict_to_obj(obj) for obj in objects]


class Edit(PermissionRequiredMixin, core.generic.views.EditView):
    template_name = 'core/directions/edit.html'
    form_class = forms.DirectionEdit
    data_method = 'post'
    pk_url_kwarg = 'number'

    def has_permission(self):
        perms = self.get_permission_required()
        return any([self.request.user.has_perm(perm) for perm in perms])

    def get_permission_required(self):
        permission_required = [self.get_edit_permission()]
        if self.request.method == 'GET' and self.kwargs.get(self.pk_url_kwarg):
            permission_required.append('core.view_direction')

        return permission_required

    def get_edit_permission(self):
        if self.kwargs.get(self.pk_url_kwarg):
            return 'core.change_direction'
        else:
            return 'core.add_direction'

    def get_success_url(self):
        return reverse_lazy('core:direction_list')

    def get_initial(self):
        initial = super().get_initial()
        obj = self.get_object()
        if obj:
            initial.update(dataclasses.asdict(obj))
            if initial.get('org'):
                initial['org'] = initial['org']['id']

            if initial.get('law_items'):
                for l_i in initial['law_items']:
                    field_name = f'law_items_{l_i["law"]["name"].replace("н", "")}'
                    if l_i["law"]["name"] == '302н':
                        field_name += f'_section_{l_i["section"]}'

                    initial.setdefault(field_name, []).append(l_i["id"])

            if initial.get('pay_method'):
                initial['pay_method'] = initial['pay_method']['id']

            if initial.get('insurance_policy'):
                initial['insurance_number'] = initial['insurance_policy']['number']

        return initial

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['current_user'] = self.request.user
        return kwargs

    def get_object(self):
        if not getattr(self, 'object', None):
            object_pk = self.kwargs.get(self.pk_url_kwarg)
            if object_pk:
                self.object = Direction.get(direction_id=object_pk)

        return self.object

    def post(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj and obj.confirm_date:
            messages.error(self.request, 'Редактирование направления запрещено: '
                                         'по нему уже создана заявка на осмотр в медицинской информационной системе')
            return super().get(request, *args, **kwargs)

        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        obj_id = self.kwargs.get(self.pk_url_kwarg)
        worker, _ = models.Worker.objects.get_or_create(
            last_name=form.cleaned_data.get('last_name'),
            first_name=form.cleaned_data.get('first_name'),
            middle_name=form.cleaned_data.get('middle_name'),
            birth=form.cleaned_data.get('birth'),
            gender=form.cleaned_data.get('gender'),
        )
        direction_dict = {
            'worker': worker,
            'insurance_policy': form.cleaned_data.get('insurance_number'),
            'org_id': form.cleaned_data.get('org'),
            'post': form.cleaned_data.get('post'),
            'shop': form.cleaned_data.get('shop'),
            'exam_type': form.cleaned_data.get('exam_type'),
            'pay_method': form.cleaned_data.get('pay_method')
        }

        if not obj_id:
            direction_id, description = Direction.create(params=form.cleaned_data)
            models.Direction.objects.create(
                mis_id=direction_id,
                **direction_dict
            )
        else:
            direction_id, description = Direction.edit(
                direction_id=obj_id,
                params=form.cleaned_data
            )
            models.Direction.objects.filter(mis_id=direction_id).update(
                **direction_dict
            )

        list_law_items = []
        for field_name in ('law_items_302_section_1', 'law_items_302_section_2', 'law_items_29'):
            list_law_items.extend(form.cleaned_data.get(field_name, []))

        direction_obj = models.Direction.objects.get(mis_id=direction_id)
        list_law_items_ids = []
        for law_item in list_law_items:
            obj, _ = models.DirectionLawItem.objects.get_or_create(
                direction=direction_obj,
                law_item_mis_id=law_item,
            )
            list_law_items_ids.append(obj.id)
        models.DirectionLawItem.objects\
            .filter(direction=direction_obj)\
            .exclude(id__in=list_law_items_ids)\
            .delete()

        if direction_id:
            messages.success(self.request, description)
            is_update = self.kwargs.get('pk')
            logger.info(
                'Направление обновлено' if is_update else 'Направление создано',
                extra={
                    'action': sw_logger.consts.ACTION_UPDATED
                              if is_update else sw_logger.consts.ACTION_CREATED,
                    'request': self.request,
                    'object': direction_obj,
                }
            )
        else:
            messages.error(self.request, description)
            return self.form_invalid(form)

        return redirect(self.get_success_url())

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['can_edit'] = True
        if not self.request.user.has_perm(self.get_edit_permission()):
            context['can_edit'] = False

        obj = self.get_object()
        if obj and obj.confirm_date:
            context['can_edit'] = False
            messages.warning(self.request, 'Редактирование направления запрещено: '
                                           'по нему уже создана заявка на осмотр в медицинской информационной системе')

        return context


class Delete(PermissionRequiredMixin, core.generic.views.DeleteView):
    success_url = reverse_lazy('core:direction_list')
    breadcrumb = 'Удалить'
    permission_required = 'core.delete_direction'
    pk_url_kwarg = 'number'

    def get_object(self, *args, **kwargs):
        if self.object is None:
            object_pk = self.kwargs.get(self.pk_url_kwarg)
            self.object = Direction.get(direction_id=object_pk)
        return self.object

    def get_breadcrumbs(self):
        direction = self.get_object()
        return [
            ('Главная', reverse('core:index')),
            ('Направления', reverse('core:direction_list')),
            (direction, reverse('core:direction_edit', kwargs={'number': direction.number})),
            (self.breadcrumb, ''),
        ]

    def delete(self, *args, **kwargs):
        pk_url_kwarg = self.kwargs.get(self.pk_url_kwarg)
        success, description = Direction.delete(direction_id=pk_url_kwarg)

        if success:
            messages.success(self.request, description)
        else:
            messages.error(self.request, description)
            return self.render_to_response(self.get_context_data())

        models.Direction.objects.filter(id=pk_url_kwarg).delete()

        return redirect(self.success_url)


class Print(PermissionRequiredMixin, core.generic.mixins.DocxMixin, View):
    permission_required = 'core.view_direction'
    print_message = 'Печать направления'

core/templates/core/directions/edit.html
{% extends 'core/base_edit.html' %}
{% load bootstrap4 %}

{% block fields %}
    <legend>Направление на осмотр {% if object.number %}№{{ object.number }}{% endif %}</legend>
    <div class="row">
        <div class="col-sm-5 border-right">
            {% bootstrap_field form.last_name layout='horizontal' %}
            {% bootstrap_field form.first_name layout='horizontal' %}
            {% bootstrap_field form.middle_name layout='horizontal' %}
            {% bootstrap_field form.birth layout='horizontal' %}
            {% bootstrap_field form.gender layout='horizontal' %}
            {% bootstrap_field form.insurance_number layout='horizontal' %}
        </div>

        <div class="col-sm-7">
            {% bootstrap_field form.org layout='horizontal' %}
            {% bootstrap_field form.post layout='horizontal' %}
            {% bootstrap_field form.shop layout='horizontal' %}
            {% bootstrap_field form.exam_type layout='horizontal' %}
            {% if form.law_items_29 in form.visible_fields %}
                {% bootstrap_field form.law_items_29 layout='horizontal' %}
            {% endif %}

            {% if form.law_items_302_section_1 in form.visible_fields and form.law_items_302_section_2 in form.visible_fields %}
                <div class="form-group row">
                    <label class="col-md-3 col-form-label" for="id_law_items_section_1">Пункты приказа 302н</label>
                    <div class="col-md-9">
                        <div class="row">
                            <div class="col-sm-6 mini-indent">
                                {% bootstrap_field form.law_items_302_section_1 show_label=False %}
                                <div class="help-block" style="margin-top: -15px">приложение 1</div>
                            </div>
                            <div class="col-sm-6 mini-indent">
                                {% bootstrap_field form.law_items_302_section_2 show_label=False %}
                                <div class="help-block" style="margin-top: -15px">приложение 2</div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endif %}
            {% bootstrap_field form.pay_method layout='horizontal' %}

            {% include 'core/directions/worker_search_include.html' %}
        </div>
    </div>
{% endblock %}

{% block buttons %}
    <div class="row">
        <div class="col-6">
            {% if object.number %}
                <a href="./delete/" class="btn btn-danger">
                    <i class="fa fa-trash"></i> Удалить
                </a>
            {% endif %}
        </div>

        <div class="col-6 text-right">
            {% if object.number %}
                <a class="btn btn-outline-secondary no-block" href="{% url 'core:direction_print' object.number %}"
                   data-toggle="tooltip" title="Распечатать направление на осмотр">
                    <i class="fa fa-print"></i> Печать
                </a>
            {% endif %}
            <button class="btn btn-success">
                <i class="fa fa-save"></i> Сохранить
            </button>
        </div>
    </div>
{% endblock %}

core/templates/core/directions/list.html
{% extends 'core/base_list.html' %}
{% load bootstrap4 %}
{% load djutils %}

{% block form %}
    <div class="row">
        <div class="col-sm-4">
            {% bootstrap_field form.last_name layout='horizontal' horizontal_label_class='col-sm-4' horizontal_field_class='col-sm-8' %}
            {% bootstrap_field form.first_name layout='horizontal' horizontal_label_class='col-sm-4' horizontal_field_class='col-sm-8' %}
            {% bootstrap_field form.middle_name layout='horizontal' horizontal_label_class='col-sm-4' horizontal_field_class='col-sm-8' %}
        </div>
        <div class="col-sm-3">
            {% bootstrap_field form.date_from layout='horizontal' horizontal_label_class='col-sm-4' horizontal_field_class='col-sm-8' %}
            {% bootstrap_field form.date_to layout='horizontal' horizontal_label_class='col-sm-4' horizontal_field_class='col-sm-8' %}
            {% bootstrap_field form.confirmed layout='horizontal' horizontal_label_class='col-sm-4' horizontal_field_class='col-sm-8' %}
        </div>
        <div class="col-sm-5">
            {% if show_orgs %}{% bootstrap_field form.orgs layout='horizontal' horizontal_label_class='col-sm-4' horizontal_field_class='col-sm-8' %}{% endif %}
            {% bootstrap_field form.shop layout='horizontal' horizontal_label_class='col-sm-4' horizontal_field_class='col-sm-8' %}
            {% bootstrap_field form.post layout='horizontal' horizontal_label_class='col-sm-4' horizontal_field_class='col-sm-8' %}
        </div>
    </div>
{% endblock %}.

{% block additional_btn %}
    {% if perms.core.add_direction %}
        <a class="btn btn-success" href="{% url 'core:direction_add' %}">
            <i class="fa fa-plus"></i> Добавить
        </a>
    {% endif %}
{% endblock %}

{% block pre_table %}
    {% if page_obj|default:object_list %}
        <span class="label label-info">Всего: {{ page_obj.paginator.count|default:object_list.count }}</span>
    {% endif %}
{% endblock pre_table %}

{% block table_head %}
    <th>№</th>
    <th>Номер</th>
    <th>ФИО</th>
    <th>Дата рождения</th>
    <th>Пол</th>
    {% if show_orgs %}<th>Организация</th>{% endif %}
    <th>Подразделение</th>
    <th>Пункты приказа</th>
    <th>Время действия</th>
    <th>Дата прохождения</th>
    <th></th>
{% endblock %}

{% block table_body %}
    <td>{{ page_obj.start_index|default:1|add:forloop.counter0 }}</td>
    <td>
        <a href="{% url 'core:direction_edit' object.number %}">{{ object.number }}</a>
    </td>
    <td>{{ object.last_name }} {{ object.first_name }} {{ object.middle_name }}</td>
    <td>{{ object.birth }}</td>
    <td>{{ object.gender }}</td>
    {% if show_orgs %}<td>{{ object.org.legal_name }}</td>{% endif %}
    <td>{{ object.shop }}</td>
    <td>
        {% for law_item in object.law_items %}
            {{ law_item }}{% if not forloop.last %}, {% endif %}
        {% endfor %}
    </td>
    <td>{% if object.from_date %}c {{ object.from_date }}{% endif %} {% if object.to_date %} по {{ object.to_date }}{% endif %}</td>
    <td>{{ object.confirm_date|default_if_none:'-' }}</td>
    <td>
        <a class="btn btn-outline-secondary" href="{% url 'core:direction_print' object.number %}" data-toggle="tooltip" title="Распечатать направление на осмотр">
            <i class="fa fa-print"></i>
        </a>
    </td>
{% endblock %}

core/templates/core/directions/worker_search_include.html
{% load static %}

<div class="worker-search-result-modal" style="display: none">
    <button type="button" class="close close-worker-search-result" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>


    <legend>Похожие сотрудники в базе МИС</legend>
    <div id="workersSearch" class="worker-search">
        <div v-if="workers.length">
            <div class="row" v-for="worker in workers">
                <div class="col-sm-12 text-left">
                    <button type="button" class="btn btn-light btn-block text-left" @click="choiceWorker(worker)">
                        [[ worker.last_name ]] [[ worker.first_name ]] [[ worker.middle_name ]] ([[ worker.birth_rus ]])
                    </button>
                </div>
            </div>
        </div>
        <div v-else>
            <div class="alert alert-warning">Похожих сотрудников не найдено</div>
        </div>
    </div>
</div>

<style>
    .worker-search-result-modal {
        background-color: #d0cfcf;
        width: 100%;
        height: 100%;
        position: absolute;
        z-index: 9;
        top: -30px;
        left: 0;
    }
</style>

<script src="{% static 'core/js/workers_search_include.js' %}"></script>