background_tasks/urls.py
from django.urls import path
from rest_framework import routers

import background_tasks.views.task
import background_tasks.views.rest

app_name = 'background_task'

urlpatterns = [
    path('', background_tasks.views.task.Search.as_view(), name='task_search'),
    path('<int:pk>/', background_tasks.views.task.Detail.as_view(), name='task_info'),
    path('<int:pk>/cancel/', background_tasks.views.task.Cancel.as_view(), name='task_cancel'),
    path('<int:pk>/restart/', background_tasks.views.task.Restart.as_view(), name='task_restart'),
]


router = routers.DefaultRouter()
router.register('rest/task', background_tasks.views.rest.TaskViewSet)
urlpatterns += router.urls

core/urls.py
from django.urls import path

from core.views import index, login
from core.views import user
from core.views import worker
from core.views import reports
from core.views import directions
from core.views import log
from core.views import rest

app_name = 'core'

urlpatterns = [
    path('', index.Index.as_view(), name='index'),

    path('user/', user.Search.as_view(), name='user'),
    path('user/add/', user.Edit.as_view(), name='user_add'),
    path('user/<int:pk>/', user.Edit.as_view(), name='user_edit'),
    path('user/<int:pk>/delete/', user.Delete.as_view(), name='user_delete'),

    path('workers/', worker.Search.as_view(), name='workers'),
    path('reports/workers_done_report/', reports.WorkersDoneReport.as_view(), name='workers_done_report'),

    path('log/', log.Log.as_view(), name='log'),

    path('directions/', directions.Search.as_view(), name='direction_list'),
    path('directions/add/', directions.Edit.as_view(), name='direction_add'),
    path('directions/<int:number>/', directions.Edit.as_view(), name='direction_edit'),
    path('directions/<int:number>/delete/', directions.Delete.as_view(), name='direction_delete'),
    path('directions/<int:number>/print/', directions.Print.as_view(), name='direction_print'),

    path('rest/orgs/', rest.Orgs.as_view(), name='rest_orgs'),
    path('rest/workers/', rest.Workers.as_view(), name='rest_workers'),
    path('rest/documents/choices/', rest.DocumentsChoices.as_view(), name='rest_documents_choices'),
    path('rest/documents/print/', rest.DocumentPrint.as_view(), name='rest_documents_print'),
    path('rest/worker_documents/', rest.WorkerDocuments.as_view(), name='rest_worker_documents'),
    path('rest/law_items/', rest.LawItems.as_view(), name='rest_law_items'),
    path('rest/generate_password/', rest.GeneratePasswordView.as_view(), name='rest_generate_password'),

    path('password_change_required/', login.PasswordChangeRequired.as_view(), name='password_change_required'),
    path('password_forgot/', login.PasswordForgot.as_view(), name='password_forgot'),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, PasswordChangeView, logout_then_login
from django.views.generic import TemplateView

import core.urls
import help.urls
import background_tasks.urls
from core.views.login import Login

urlpatterns = [
    path('', include(core.urls, namespace='core')),
    path('help/', include(help.urls, namespace='help')),
    path('background_tasks/', include(background_tasks.urls, namespace='background_tasks')),
    path('admin/', admin.site.urls),

    path('login/', Login.as_view(), name='login'),
    path('logout/', logout_then_login, {'login_url': '/login/?next=/'}, name='logout'),

    path('password_change/', PasswordChangeView.as_view(template_name='core/password_change.html',
                                                        success_url='/logout/'), name='password_change'),
]

handler403 = 'core.views.response_forbidden_handler'
handler404 = 'core.views.response_not_found_error_handler'
handler500 = 'core.views.response_server_error_handler'

if settings.DEBUG:
    urlpatterns += static('node_modules', document_root=settings.BASE_DIR + '/node_modules')
    urlpatterns += static('media', document_root=settings.MEDIA_ROOT)

    urlpatterns = [
        # для отладки страниц ошибок
        path('403/', TemplateView.as_view(template_name='core/errors/403.html')),
        path('404/', TemplateView.as_view(template_name='core/errors/404.html')),
        path('500/', TemplateView.as_view(template_name='core/errors/500.html')),
    ] + urlpatterns

background_tasks/models.py
import os
import pickle
import tempfile
from typing import Callable, Dict
import importlib

from django.conf import settings
from django.contrib.auth import get_user_model
from django.core.files import File
from django.core.validators import MaxValueValidator
from django.db import models
import core.models
from background_tasks import consts

User = get_user_model()


class Task(models.Model):
    name = models.CharField('Название задачи', max_length=255)
    description = models.TextField('Описание задачи', blank=True)
    user = models.ForeignKey(User, verbose_name='Пользователь', null=True, blank=True,
                             related_name='background_tasks', help_text='Пользователь, создавший задачу',
                             on_delete=models.PROTECT)

    func_path = models.CharField('Функция для вызова', max_length=255)
    params = models.FileField('Параметры', null=True, blank=True,
                              upload_to=lambda t, f_name: 'background_tasks/params_pickle/%s/%s' % (t.id, f_name),
                              help_text='Параметры, сериализованные в формате pickle')

    status = models.CharField('Статус выполнения задачи', choices=consts.STATUS_CHOICES,
                              default=consts.STATUS_PENDING, max_length=255, db_index=True)
    percent = models.PositiveSmallIntegerField('Процент выполнения', default=0, validators=[MaxValueValidator(100)])

    created_dt = models.DateTimeField('Создана', auto_now_add=True)
    start_dt = models.DateTimeField('Время начала выполнения задачи', null=True, blank=True)
    finish_dt = models.DateTimeField('Время окончания выполнения задачи', null=True, blank=True)

    result_attachment = models.FileField('Результат', null=True, blank=True,
                                         upload_to=lambda t, f_name: 'background_tasks/results/%s/%s' % (t.id, f_name))

    class Meta:
        verbose_name = 'Фоновая задача'
        verbose_name_plural = 'Фоновые задачи'
        ordering = ('-created_dt', )

    @classmethod
    def create_task(cls, method: Callable, name: str, user: 'core.models.DjangoUser', params: Dict,
                    description: str = '') -> 'Task':
        from background_tasks.tasks import start_task

        func_path = f"{method.__self__.__module__}.{method.__self__.__qualname__}.{method.__name__}"
        task = cls.objects.create(
            name=name,
            description=description,
            user=user,
            func_path=func_path
        )

        task.save_params(params)
        start_task.delay(task.id)

        return task

    @staticmethod
    def pickle_params(params: dict) -> str:
        """Сериализует параметры и возвращает путь к файлу с сериализованными данными"""
        if not os.path.exists(settings.DIR_FOR_TMP_FILES):
            os.makedirs(settings.DIR_FOR_TMP_FILES)

        pickled_path = tempfile.mkdtemp(dir=settings.DIR_FOR_TMP_FILES) + '/data.pickle'

        with open(pickled_path, 'wb') as f:
            pickle.dump(params, f)

        return pickled_path

    def save_params(self, params: dict):
        pickled_params_path = self.pickle_params(params)
        with open(pickled_params_path, 'rb') as f:
            self.params.save(name='params.pickle', content=File(f))
        os.unlink(pickled_params_path)

    def __str__(self):
        return self.name

    def get_func(self) -> Callable:
        try:
            # функция в пакете
            module_path = '.'.join(i for i in self.func_path.split('.')[:-1])
            func_name = self.func_path.split('.')[-1]
            module = importlib.import_module(module_path)
            return getattr(module, func_name)
        except ImportError:
            # метод класса
            module_path = '.'.join(i for i in self.func_path.split('.')[:-2])
            class_name = self.func_path.split('.')[-2]
            func_name = self.func_path.split('.')[-1]
            module = importlib.import_module(module_path)
            class_obj = getattr(module, class_name)
            return getattr(class_obj, func_name)

    def get_params(self) -> dict:
        if self.params:
            with open(self.params.path, 'rb') as f:
                return pickle.load(self.params)
        else:
            return {}

    def is_success(self) -> bool:
        return self.finish_dt and self.status == consts.STATUS_COMPLETE

    def is_fail(self) -> bool:
        return self.status == consts.STATUS_FAIL

    def in_progress(self) -> bool:
        return self.status == consts.STATUS_IN_PROCESS


class Log(models.Model):
    task = models.ForeignKey(Task, related_name='logs', on_delete=models.CASCADE)
    description = models.TextField('Описание')
    status = models.CharField('Статус выполнения задачи', choices=consts.STATUS_CHOICES,
                              default=consts.STATUS_IN_PROCESS, max_length=255, db_index=True)
    dc = models.DateTimeField('Создана', auto_now_add=True)

    class Meta:
        verbose_name = 'Запись журнала выполнения задачи'
        verbose_name_plural = 'Журнал выполнения задачи'
        ordering = ('-dc', )

    def is_success(self) -> bool:
        return self.status == consts.STATUS_COMPLETE

    def is_fail(self) -> bool:
        return self.status == consts.STATUS_FAIL

core/models.py
import json
from typing import List

import djutils.models
import sw_logger.models
from django.db import models
from django.contrib.auth.models import User as DjangoUser
from sw_logger.tools import get_model_by_log_name
from core import consts

from mis.document import DocumentType
from mis.org import Org


def docx_file_extension(value):
    """Валидация раширения файла для FileField(validators=[docx_file_extension])"""
    import os
    from django.core.exceptions import ValidationError
    ext = os.path.splitext(value.name)[1]  # [0] returns path+filename
    valid_extensions = ['.docx']
    if not ext.lower() in valid_extensions:
        raise ValidationError('Поддерживается только формат файла docx.')


class Status(djutils.models.OneValueModel):
    WORKER_LOAD_TIME = 'worker_load_time'

    class Meta:
        verbose_name = 'Статус'
        verbose_name_plural = 'Статусы'

    def __str__(self):
        return self.name


class User(models.Model):
    django_user = models.OneToOneField(DjangoUser, related_name='core', on_delete=models.CASCADE)
    org_ids = models.TextField('ID организаций', help_text='список id организаций из внешней системы')
    post = models.CharField('Должность', max_length=255, blank=True)
    need_change_password = models.BooleanField('Нужно сменить пароль', default=True)

    class Meta:
        permissions = (
            ('view_workers_done_report', 'Просмотр отчета по прошедшим'),
            ('view_money', 'Просмотр денежной информации'),

            ('view_direction', 'Просмотр направлений на осмотр'),
            ('add_direction', 'Создание направлений на осмотр'),
            ('change_direction', 'Редактирование направлений на осмотр'),
            ('delete_direction', 'Удаление направлений на осмотр'),
        )

    def __str__(self):
        return str(self.django_user)

    def get_fio(self):
        return ' '.join(filter(bool, [self.django_user.last_name, self.django_user.first_name]))

    def get_short_fio(self):
        if self.django_user.first_name.strip():
            return f'{self.django_user.last_name} {self.get_initials()}'
        else:
            return self.get_fio()

    def get_initials(self):
        if not self.django_user.first_name.strip():
            return ''

        parts = self.django_user.first_name.split(' ')
        if not parts:
            return ''

        initials = '%s.' % parts[0][0]
        if len(parts) > 1:
            initials += '%s.' % parts[1][0]
        return initials

    def get_org_ids(self):
        if not self.org_ids:
            return []
        return json.loads(self.org_ids)

    def get_orgs(self) -> List[Org]:
        if not self.org_ids:
            return []

        return [Org.get(org_id=org_id) for org_id in self.get_org_ids()]

    def get_available_document_types(self) -> List[DocumentType]:
        user_doc_type_ids = self.available_document_type_ids.values_list('document_type_id', flat=True)
        return [DocumentType.get(document_type_id=d_t_id) for d_t_id in user_doc_type_ids]


class UserAvailableDocumentType(models.Model):
    user = models.ForeignKey(User, verbose_name='Пользователь', on_delete=models.CASCADE,
                             related_name='available_document_type_ids')
    document_type_id = models.IntegerField('ID вида документа в МИС')

    class Meta:
        verbose_name = 'Доступный вид документа для пользователя'
        verbose_name_plural = 'Доступные виды документов для пользователей'
        unique_together = ('user', 'document_type_id')


class Worker(models.Model):
    last_name = models.CharField(max_length=255, verbose_name='Фамилия')
    first_name = models.CharField(max_length=255, verbose_name='Имя')
    middle_name = models.CharField(max_length=255, verbose_name='Отчество', blank=True)
    gender = models.CharField(max_length=7, verbose_name='Пол', choices=consts.GENDER_CHOICE)
    birth = models.DateField(verbose_name='Дата рождение')
    note = models.TextField(blank=True, verbose_name='Примечание')

    class Meta:
        verbose_name = 'Сотрудник'
        verbose_name_plural = 'Сотрудники'
        ordering = ['last_name', 'first_name', 'middle_name']
        permissions = (
            ('view_workers_document', 'Просмотр документов сотрудника'),
        )

    def __str__(self):
        return ' '.join(filter(bool, [self.last_name, self.first_name, self.middle_name]))

    def get_posts(self):
        return ', '.join(set(self.worker_orgs.exclude(post="").values_list('post', flat=True)))

    def get_shops(self):
        return ', '.join(set(self.worker_orgs.exclude(shop="").values_list('shop', flat=True)))


class WorkerOrganization(models.Model):
    worker = models.ForeignKey(Worker, on_delete=models.CASCADE, verbose_name='Сотрудник', related_name='worker_orgs')
    mis_id = models.IntegerField(verbose_name='МИС id')
    org_id = models.IntegerField(verbose_name='Организация id')
    post = models.CharField(max_length=512, verbose_name='Должность')
    shop = models.CharField(max_length=512, verbose_name='Подразделение', blank=True)
    start_work_date = models.DateField(null=True, blank=True, verbose_name='Дата приема')
    end_work_date = models.DateField(null=True, blank=True, verbose_name='Дата уволения')

    class Meta:
        verbose_name = 'Сотрудник организации'
        verbose_name_plural = 'Сотрудники организации'


class DirectionDocxTemplate(models.Model):
    name = models.CharField('Название', max_length=255, unique=True)
    description = models.TextField('Описание', blank=True)
    org_ids = models.CharField('Список ID организаций', max_length=255,
                               help_text='список id организаций из внешней системы', blank=True)
    file = models.FileField('Файл шаблона', upload_to='core/direction_docx_templates/',
                            validators=[docx_file_extension])

    class Meta:
        verbose_name = 'Шаблон направления на осмотр'
        verbose_name_plural = 'Шаблоны направлений на осмотр'
        ordering = ('name', )

    def __str__(self):
        return self.name

    def get_orgs(self) -> List[Org]:
        if not self.org_ids:
            return []

        return [Org.get(org_id=org_id) for org_id in json.loads(self.org_ids)]


class Log(sw_logger.models.Log):

    class Meta:
        ordering = ('id',)
        verbose_name = 'Запись в журнале'
        verbose_name_plural = 'Журнал'

    def get_model_object(self, include_deleted=True):
        model = get_model_by_log_name(self.object_name)
        manager = 'standard_objects' if hasattr(model, 'standard_objects') and include_deleted else 'objects'
        return getattr(model, manager).filter(id=self.object_id).first()

core/views/admin.py
from django.conf import settings
from django.views.generic import TemplateView
from django.contrib.auth.mixins import PermissionRequiredMixin


class Management(PermissionRequiredMixin, TemplateView):
    template_name = 'core/admin.html'
    permission_required = 'core.view_management'

core/views/index.py
from django.conf import settings
from django.views.generic import TemplateView


class Index(TemplateView):
    template_name = settings.TEMPLATES_DICT.get("index")

core/views/log.py
import core.generic.mixins
import core.generic.views
from django.contrib.auth.mixins import PermissionRequiredMixin

from core import models, forms, filters


class Log(PermissionRequiredMixin, core.generic.mixins.FormMixin, core.generic.views.ListView):
    template_name = 'core/log.html'
    model = models.Log
    form_class = forms.Log
    filter_class = filters.Log
    title = 'Журнал'
    permission_required = 'core.view_log'

    def get_queryset(self):
        return super().get_queryset().order_by('-created')

core/templates/core/admin.html
{% extends BASE_TEMPLATE %}

{% block container %}
     <div class="index-content">
        <div class="row">
            <div class="col-sm-12 text-center">
                 {% if perms.auth.view_user %}
                     <a class="btn btn-index-primary index-btn" href="{% url 'core:user' %}">
                         <p><i class="fa fa-users"></i></p>
                         Пользователи
                    </a>
                {% endif %}

                {% if perms.auth.view_log %}
                     <a class="btn btn-index-primary index-btn" href="{% url 'core:log' %}">
                         <p><i class="fa fa-clock-o "></i></p>
                         Журнал
                    </a>
                {% endif %}
            </div>
        </div>
     </div>
{% endblock %}

core/templates/core/base.html
<!DOCTYPE html>
<html lang="ru">

<head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="robots" content="noindex, nofollow " />
    <meta name="description" content="">
    <meta name="author" content="">

    {% block title %}<title>{{ title }} {% if not title %}Портал{% endif %}</title>{% endblock %}

    {% block base_style %}
        <link href="/node_modules/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
        <link href="/node_modules/font-awesome/css/font-awesome.css" rel="stylesheet">
        <link href="/node_modules/select2/dist/css/select2.css" rel="stylesheet">
        <link href="/node_modules/jquery-ui/themes/base/all.css" rel="stylesheet">
        <link href="/node_modules/jquery-toast-plugin/dist/jquery.toast.min.css" rel="stylesheet">
        <link href="/node_modules/select2-bootstrap-theme/dist/select2-bootstrap.css" rel="stylesheet">
        <link href="/node_modules/select2-bootstrap-theme/dist/select2-bootstrap.min.css" rel="stylesheet">
    {% endblock %}

    {% block base_js %}
        <script src="/node_modules/jquery/dist/jquery.js"></script>
        <script src="/node_modules/jquery-ui-dist/jquery-ui.min.js"></script>
        <script src="/node_modules/jquery-ui/ui/i18n/datepicker-ru.js"></script>
        <script src="/node_modules/jquery.maskedinput/src/jquery.maskedinput.js"></script>
        <script src="/node_modules/jquery-toast-plugin/dist/jquery.toast.min.js"></script>
        <script src="/node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="/node_modules/select2/dist/js/select2.js"></script>
        <script src="/node_modules/select2/dist/js/i18n/ru.js"></script>

        {# для прода используем min версию, чтобы не выпадали не нужные комменты #}
         {% if debug %}
            <script src="/node_modules/vue/dist/vue.js"></script>
         {% else %}
             <script src="/node_modules/vue/dist/vue.min.js"></script>
         {% endif %}
    {% endblock %}

    {% block css %}
        <link href="{% static "core/css/style.css" %}" rel="stylesheet">
    {% endblock %}

    {% block form_media %}
        {{ form.media }}
        {{ formset.media }}
    {% endblock form_media %}

</head>

<body>
    {% block body %}
        {% block pre_navbar %}
            <div class="container med-center-detail">
                <div class="row">
                    <div class="col-sm-3">
                        {% block pre_navbar_logo %}
                        {% endblock %}
                    </div>
                    {% block pre_navbar_user %}
                        <div class="col-sm-9 text-right">
                            {% if user.is_authenticated %}
                                <div class="dropdown dropdown-user">
                                    <a class="dropdown-toggle" href="#" id="navbarDropdownBlog" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <i class="fa fa-user"></i> {{ user.core.get_fio|default:user.username }}
                                    </a>
                                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownBlog">
                                        {% if user.is_staff %}
                                            <a class="dropdown-item" href="/admin/">
                                                <i class="fa fa-cogs"></i> Панель администратора
                                            </a>
                                        {% endif %}
                                        <a class="dropdown-item" href="{% url 'password_change' %}">
                                            <i class="fa fa-edit"></i> Сменить пароль
                                        </a>
                                        <a class="dropdown-item" href="{% url 'logout' %}">
                                            <i class="fa fa-sign-out"></i> Выход
                                        </a>
                                    </div>
                                </div>
                            {% endif %}
                        </div>
                    {% endblock %}
                </div>
            </div>
        {% endblock %}

        {% block navbar %}
            <nav class="navbar navbar-expand-lg">
                <div class="container">
                    <a class="navbar-brand" href="/">Личный кабинет</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarText">
                        <ul class="navbar-nav navbar-center">
{#                            {% if user.is_authenticated and request.path != '/' %}#}
                                {% if perms.core.view_worker %}
                                    <li class="nav-item">
                                        <a class="nav-link" href="{% url 'core:workers' %}">Сотрудники</a>
                                    </li>
                                {% endif %}
                                {% if perms.core.view_workers_done_report %}
                                    <li class="nav-item">
                                        <a class="nav-link" href="{% url 'core:workers_done_report' %}">Отчет по прошедшим</a>
                                    </li>
                                {% endif %}
                                {% if perms.core.view_direction %}
                                    <li class="nav-item">
                                        <a class="nav-link" href="{% url 'core:direction_list' %}">Направления</a>
                                    </li>
                                {% endif %}
                                {% if perms.auth.view_user %}
                                    <li class="nav-item">
                                        <a class="nav-link" href="{% url 'core:user' %}">Пользователи</a>
                                    </li>
                                {% endif %}
                                {% if user_background_tasks.count or user.is_superuser%}
                                    <li class="nav-item">
                                        <a class="nav-link" href="{% url 'background_tasks:task_search' %}">
                                            Фоновые задачи
                                        </a>
                                    </li>
                                {% endif %}
{#                            {% endif %}#}
                        </ul>
                    </div>
                </div>
            </nav>
        {% endblock %}

        {% block page_content %}
            <!-- Page Content -->
            <div class="container page-content">
                {# django-messages (используются, например, при сообщении о сохранении, ошибках формы и т.п.) #}
                {% block messages %}
                    {% if messages %}
                        <ul class="list-group">
                            {% for message in messages %}
                                <li class="list-group-item alert alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %}">
                                    {% if message.tags == 'warning' %}<i class="fa fa-warning"></i>{% endif %}
                                    {{ message }}
                                </li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                {% endblock %}

                {% block container %}{% endblock %}
            </div>
        {% endblock %}

        {% block footer %}
            <footer class="text-center">
                <a href='https://github.com/Egorka96/med-org-portal' target='_blank'>&copy; Egor Razzhivkin 2020 - 2021</a>
            </footer>
        {% endblock %}

        {% block loader %}
            <div id="loading" style="display: none; position: fixed; top:0; min-width: 100%; background-color: rgba(255, 255, 255, 0.76);
        min-height: 100%; z-index: 1000;">
                <img src="{% static "core/img/load.gif" %}"
                     style="box-shadow: white 0 0 300px 200px; position: fixed; top: 39%; left: 46%">
            </div>
        {% endblock %}

        {% block js %}
            <script>
                $.ajaxSetup({
                    headers: { "X-CSRFToken": '{{csrf_token}}' }
                });

                $(function() {
                    $('.date').datepicker({dateFormat: 'dd.mm.yy'});
                    $('.hasDatepicker').mask('99.99.9999');
                    $('input[type=text]:not(.allow-autocomplete)').prop('autocomplete', 'off');     // отключаю браузреный автокомплит форм
                    $.fn.select2.defaults.set("theme", "bootstrap");
                    $('.need-select2').select2({
                        width: '100%',
                        language: "ru",
                        theme: "bootstrap"
                    });

                    $('[data-toggle="tooltip"]').tooltip();
                    $('[data-toggle="popover"]').popover();

                    // вешаем на сабмит лоадер
                    $('form').submit(function(e) {
                        {#console.log(e);#}

                        // пропустим формы, для которых лоадер не нужен
                        if ($(this).hasClass('no-submit-loader'))
                            return;

                        $('#loading').show()
                    });

                    $('#clearForm').click(function () {
                        $(':input', 'form')
                            .not(':button, :submit, :reset, :hidden')
                            .removeAttr('checked')
                            .removeAttr('selected')
                            .not(':radio, .no-clean')
                            .val('').trigger('change');
                    });

                    let current = location.pathname;
                    $('.navbar-nav li a').each(function(){
                        let $this = $(this);
                        // if the current path is like this link, make it active
                        if (current.indexOf($this.attr('href')) !== -1){
                            $this.addClass('nav-link-active');
                        }
                    })
                })
            </script>
        {% endblock %}
    {% endblock %}
</body>
</html>

core/templates/core/index.html
{% extends BASE_TEMPLATE %}

{% block container %}
    <div class="index-content">
        <div class="row">
            <div class="col-sm-12 text-center">
                {% if perms.core.view_worker %}
                    <a class="btn btn-index-info index-btn" href="{% url 'core:workers' %}">
                         <p><i class="fa fa-users"></i></p>
                            Сотрудники
                            <p class="index-btn-small-text">сотрудники организации</p>
                    </a>
                {% endif %}

                {% if perms.core.view_workers_done_report %}
                    <a class="btn btn-index-primary index-btn" href="{% url 'core:workers_done_report' %}">
                         <p><i class="fa fa-list"></i></p>
                            Прошедшие
                            <p class="index-btn-small-text">отчет по прошедшим</p>
                    </a>
                {% endif %}

                {% if perms.core.view_direction %}
                     <a class="btn btn-index-info index-btn" href="{% url 'core:direction_list' %}">
                         <p><i class="fa fa-address-card"></i></p>
                         Направления
                         <p class="index-btn-small-text">сотрудников на осмотр</p>
                    </a>
                {% endif %}

                 {% if perms.auth.view_management %}
                     <a class="btn btn-index-primary index-btn" href="{% url 'core:management' %}">
                         <p><i class="fa fa-cogs"></i></p>
                         Администрирование
                    </a>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

core/templates/core/login.html
{% extends BASE_TEMPLATE %}
{% load bootstrap4 %}

{% block container %}
    <br>

    <div class="row">
        <div class="col-md-6 offset-md-3">
            <form action="" method="POST">
                {% csrf_token %}
                {% bootstrap_form form %}
                <button type="submit" class="btn btn-primary btn-block btn-login">Войти</button>
                {% if can_send_email_user_credentials %}
                    <div class="row">
                        <div class="col-md-12 text-center">
                            <a href="{% url 'core:password_forgot' %}">Забыли пароль?</a>
                        </div>
                    </div>
                {% endif %}
            </form>
        </div>
    </div>
{% endblock container %}