core/urls.py
from django.urls import path

from core.views import index, login
from core.views import user
from core.views import worker
from core.views import reports
from core.views import directions
from core.views import log
from core.views import rest

app_name = 'core'

urlpatterns = [
    path('', index.Index.as_view(), name='index'),

    path('user/', user.Search.as_view(), name='user'),
    path('user/add/', user.Edit.as_view(), name='user_add'),
    path('user/<int:pk>/', user.Edit.as_view(), name='user_edit'),
    path('user/<int:pk>/delete/', user.Delete.as_view(), name='user_delete'),

    path('workers/', worker.Search.as_view(), name='workers'),
    path('reports/workers_done_report/', reports.WorkersDoneReport.as_view(), name='workers_done_report'),

    path('log/', log.Log.as_view(), name='log'),

    path('directions/', directions.Search.as_view(), name='direction_list'),
    path('directions/add/', directions.Edit.as_view(), name='direction_add'),
    path('directions/<int:number>/', directions.Edit.as_view(), name='direction_edit'),
    path('directions/<int:number>/delete/', directions.Delete.as_view(), name='direction_delete'),
    path('directions/<int:number>/print/', directions.Print.as_view(), name='direction_print'),

    path('rest/orgs/', rest.Orgs.as_view(), name='rest_orgs'),
    path('rest/workers/', rest.Workers.as_view(), name='rest_workers'),
    path('rest/documents/choices/', rest.DocumentsChoices.as_view(), name='rest_documents_choices'),
    path('rest/documents/print/', rest.DocumentPrint.as_view(), name='rest_documents_print'),
    path('rest/worker_documents/', rest.WorkerDocuments.as_view(), name='rest_worker_documents'),
    path('rest/law_items/', rest.LawItems.as_view(), name='rest_law_items'),
    path('rest/generate_password/', rest.GeneratePasswordView.as_view(), name='rest_generate_password'),

    path('password_change_required/', login.PasswordChangeRequired.as_view(), name='password_change_required'),
    path('password_forgot/', login.PasswordForgot.as_view(), name='password_forgot'),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, PasswordChangeView, logout_then_login
from django.views.generic import TemplateView

import core.urls
import help.urls
import background_tasks.urls
from core.views.login import Login

urlpatterns = [
    path('', include(core.urls, namespace='core')),
    path('help/', include(help.urls, namespace='help')),
    path('background_tasks/', include(background_tasks.urls, namespace='background_tasks')),
    path('admin/', admin.site.urls),

    path('login/', Login.as_view(), name='login'),
    path('logout/', logout_then_login, {'login_url': '/login/?next=/'}, name='logout'),

    path('password_change/', PasswordChangeView.as_view(template_name='core/password_change.html',
                                                        success_url='/logout/'), name='password_change'),
]

handler403 = 'core.views.response_forbidden_handler'
handler404 = 'core.views.response_not_found_error_handler'
handler500 = 'core.views.response_server_error_handler'

if settings.DEBUG:
    urlpatterns += static('node_modules', document_root=settings.BASE_DIR + '/node_modules')
    urlpatterns += static('media', document_root=settings.MEDIA_ROOT)

    urlpatterns = [
        # для отладки страниц ошибок
        path('403/', TemplateView.as_view(template_name='core/errors/403.html')),
        path('404/', TemplateView.as_view(template_name='core/errors/404.html')),
        path('500/', TemplateView.as_view(template_name='core/errors/500.html')),
    ] + urlpatterns

core/forms.py
import datetime
import json

from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.password_validation import validate_password

from core import models
from mis.law_item import LawItem, Law
from mis.org import Org
from mis.service_client import Mis
from mis.pay_method import PayMethod as MisPayMethod
from mis.document import DocumentType as MisDocumentType
import sw_logger.forms

User = get_user_model()


class RusDateField(forms.DateField):
    def __init__(self, input_format='%d.%m.%Y', *args, **kwargs):
        kwargs['input_formats'] = [input_format]
        if 'initial' not in kwargs:
            kwargs['initial'] = lambda: datetime.date.today().strftime('%d.%m.%Y')
        if 'widget' not in kwargs:
            kwargs['widget'] = forms.TextInput(attrs={'class': 'date'})
        super().__init__(*args, **kwargs)
        self.input_format = input_format

    def to_python(self, value):
        if value:
            # если уже дата вернем как есть
            if isinstance(value, datetime.datetime):
                return value.date()
            if isinstance(value, datetime.date):
                return value
            try:
                return datetime.datetime.strptime(value, self.input_format).date()
            except ValueError:
                raise forms.ValidationError(self.error_messages['invalid'])
        else:
            return None

    def validate(self, value):
        super(RusDateField, self).validate(value)
        if not value:
            return

        if value.year < 1900:
            raise forms.ValidationError(u'Год должен быть больше 1900')

        if isinstance(value, datetime.date):
            return

        try:
            return datetime.datetime.strptime(value, self.input_format).date()
        except ValueError:
            raise forms.ValidationError(u'Используйте формат ДД.ММ.ГГГГ')

    def prepare_value(self, value):
        if isinstance(value, datetime.date):
            return value.strftime(self.input_format)
        return value


class ExtraChoiceField(forms.ChoiceField):
    @staticmethod
    def valid_value(*args, **kwargs) -> bool:
        return True


class ListField(forms.MultipleChoiceField):
    @staticmethod
    def valid_value(*args, **kwargs) -> bool:
        return True


class FIO(forms.Form):
    last_name = forms.CharField(label='Фамилия', required=False)
    first_name = forms.CharField(label='Имя', required=False)
    middle_name = forms.CharField(label='Отчество', required=False)


class PayMethod(forms.Form):
    pay_method = ExtraChoiceField(label='Способ оплаты', choices=[], required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['pay_method'].widget.choices = [('', '----------')] + \
                                                   [(p_m.id, p_m.name) for p_m in MisPayMethod.filter()]


class OrgsMixin(forms.Form):
    org = ExtraChoiceField(label='Организация', choices=[], required=False)
    orgs = ListField(label='Организации', choices=[], required=False)

    class Media:
        js = ['core/js/orgs.js']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in ('org', 'orgs'):
            choices = []
            values = self.data.getlist(field) if hasattr(self.data, 'getlist') else None
            if not values:
                values = self.initial.get(field, [])

            if not isinstance(values, list):
                values = [values]

            if values:
                for value in values:
                    if not value:
                        continue

                    org = Org.get(org_id=value)
                    choices.append((org.id, str(org)))

            self.fields[field].widget.choices = choices


class LawItems(forms.Form):
    law_items_302_section_1 = ListField(label='Пункты приказа 302н прил.1', required=False, choices=[])
    law_items_302_section_2 = ListField(label='Пункты приказа 302н прил.2', required=False, choices=[])
    law_items_29 = ListField(label='Пункты приказа 29н', required=False, choices=[])

    class Media:
        js = ['core/js/law_items.js']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in ('law_items_302_section_1', 'law_items_302_section_2', 'law_items_29'):
            choices = []
            values = self.data.getlist(field) if hasattr(self.data, 'getlist') else None
            if not values:
                values = self.initial.get(field, [])

            if values and not isinstance(values, list):
                values = [values]

            if values:
                for value in values:
                    law_item = LawItem.get(law_item_id=value)
                    choices.append((law_item.id, law_item.name))

            self.fields[field].widget.choices = choices

        # возьмем активные приказы из МИС
        active_law_names = [l.name for l in Law.filter({'active': True})]
        if '29н' not in active_law_names and not self.fields['law_items_29'].choices:
            self.fields['law_items_29'].widget = forms.MultipleHiddenInput()

        if '302н' not in active_law_names and \
                not (self.fields['law_items_302_section_1'].widget.choices or self.fields['law_items_302_section_2'].widget.choices):
            self.fields['law_items_302_section_1'].widget = forms.MultipleHiddenInput()
            self.fields['law_items_302_section_2'].widget = forms.MultipleHiddenInput()

    def clean(self):
        law_items_302n = [*self.cleaned_data.get('law_items_302_section_1', []),
                          *self.cleaned_data.get('law_items_302_section_2', [])]
        law_items_29n = self.cleaned_data.get('law_items_29', [])

        if law_items_302n and law_items_29n:
            raise forms.ValidationError('Необходимо указать пункты приказа 302н ИЛИ 29н.')

        return self.cleaned_data


class DocumentTypeMixin(forms.Form):
    document_types = ListField(label='Виды документов', help_text='для печати из МИС', required=False, choices=[],
                               widget=forms.SelectMultiple(attrs={'class': 'need-select2'}))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['document_types'].widget.choices = [(d_t.id, d_t.name) for d_t in MisDocumentType.filter()]


class DateFromTo(forms.Form):
    date_from = RusDateField(label='С', required=False, initial=None)
    date_to = RusDateField(label='По', required=False, initial=None)


class ExamTypeMixin(forms.Form):
    EXAM_TYPE_CHOICES = (
        ('', '---------'),
        ('Предварительный', 'Предварительный'),
        ('Периодический', 'Периодический'),
        ('Внеочередной', 'Внеочередной'),
    )
    exam_type = forms.ChoiceField(label='Вид осмотра', required=False, choices=EXAM_TYPE_CHOICES)


class PlaceMixin(forms.Form):
    PLACE_CHOICES = (
        ('', '---------'),
        ('Медцентр', 'Медцентр'),
        ('Выезд', 'Выезд'),
    )
    place = forms.ChoiceField(label='Место', help_text='место проведения осмотра', choices=PLACE_CHOICES,
                              required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        if not Mis().is_out_used():
            self.fields['place'].widget = forms.HiddenInput()


class UserSearch(forms.Form):
    username = forms.CharField(label='Логин', required=False)
    last_name = forms.CharField(label='Фамилия', required=False)
    is_active = forms.NullBooleanField(label='Активен', required=False, initial=True)


class UserEdit(OrgsMixin, DocumentTypeMixin, forms.ModelForm):
    new_password = forms.CharField(label='Новый пароль', required=False, validators=[validate_password],
                                   help_text='<div>Пароль не должен совпадать с именем или другой персональной '
                                             'информацией пользователя или быть слишком похожим на неё. </div>'
                                             '<div>Пароль должен содержать как минимум 8 символов. </div>'
                                             '<div>Пароль не может быть одним из широко распространённых паролей. </div>'
                                             '<div>Пароль не может состоять только из цифр. </div>')
    post = forms.CharField(label='Должность', required=False)

    class Meta:
        model = User
        exclude = ['password', 'date_joined', 'last_login', 'is_staff', ]
        widgets = {
            'groups': forms.SelectMultiple(attrs={'class': 'need-select2'}),
            'user_permissions': forms.SelectMultiple(attrs={'class': 'need-select2'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Логин'
        self.fields['email'].label = 'Email'
        self.fields['email'].help_text = 'адрес электронной почты'

        if getattr(self.instance, 'core', None):
            orgs = self.instance.core.get_orgs()
            self.initial['orgs'] = [str(org.id) for org in orgs]
            self.fields['orgs'].widget.choices = [(str(org.id), org.name) for org in orgs]

            self.initial['document_types'] = [str(d_t.id) for d_t in self.instance.core.get_available_document_types()]
            self.initial['post'] = self.instance.core.post

        self.fields['orgs'].help_text = 'к каким организациям пользователь должен иметь доступ. ' \
                                        'Оставьте поле пустым, если пользователь должен иметь доступ ко всем ' \
                                        'доступным организациям'
        self.fields['document_types'].help_text = 'какие виды документов доступны пользователю для печати'

    def clean_email(self):
        value = self.cleaned_data.get('email')
        if not value:
            return

        # будем требовать, чтобы email пользователей был уникален

core/generic/views.py
import sys
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect

from django.views.generic import (
    ListView as DjangoListView,
    UpdateView as DjangoUpdateView,
    DeleteView as DjangoDeleteView,
)

from core.generic import mixins


class ListView(mixins.ExcelMixin, mixins.BreadcrumbsMixin, mixins.TitleMixin, DjangoListView):
    DEFAULT_PAGINATE_BY = 50

    def get_paginate_by(self, queryset=None):
        paginate_by = self.request.session.get(f'per_page-{self.request.path}',
                                               self.paginate_by or self.DEFAULT_PAGINATE_BY)
        per_page = self.request.GET.get('per_page')
        if per_page:
            self.request.session[f'per_page-{self.request.path}'] = per_page
            paginate_by = per_page

        return paginate_by if paginate_by != 'all' else sys.maxsize

    def get_page_numbers(self, queryset=None):

        if queryset is None:
            queryset = self.get_queryset()

        numbers = []
        if queryset:
            page = int(self.request.GET.get('page', 1))
            per_page = self.get_paginate_by(queryset)

            pag = self.get_paginator(queryset, per_page or len(queryset))
            all_numbers = list(pag.page_range)

            start = page - 4 if page - 4 > 1 else 0
            end = page + 3
            numbers = all_numbers[start:end]

        has_left = False
        has_right = False
        if numbers:
            has_left = numbers[0] != all_numbers[0]
            has_right = numbers[-1] != all_numbers[-1]

        return has_left, numbers, has_right

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        queryset = None
        if hasattr(self, 'object_list'):
            queryset = self.object_list

        has_left, numbers, has_right = self.get_page_numbers(queryset=queryset)
        context['page_has_left'] = has_left
        context['page_numbers'] = numbers
        context['page_has_right'] = has_right
        return context

    def get_filter_params(self):
        form = self.get_form()
        if form.is_valid():
            filter_params = form.cleaned_data
        else:
            filter_params = self.get_initial()

        return filter_params

    def get_queryset(self):
        queryset = self.filter_class(
            data=self.get_filter_params(),
            request=self.request,
        ).qs
        return queryset.distinct()


class EditView(mixins.BreadcrumbsMixin, mixins.TitleMixin, mixins.FormMixin, DjangoUpdateView):
    object = None

    def get_object(self):
        object_pk = self.kwargs.get(self.pk_url_kwarg)
        if object_pk:
            self.object = get_object_or_404(self.model, pk=object_pk)

        return self.object

    def get_title(self):
        if obj := self.get_object():
            return str(obj)
        else:
            return 'Создание'

    def form_valid(self, form):
        form.save()
        return redirect(self.get_success_url())


class DeleteView(mixins.BreadcrumbsMixin, mixins.TitleMixin, DjangoDeleteView):
    object = None
    delete_message = None
    template_name = 'core/base_delete.html'

    def get_delete_message(self):
        return self.delete_message or str(self.object)

    def get_object(self, queryset=None):
        if not self.object:
            self.object = super().get_object(queryset=queryset)

        return self.object

    def get_title(self):
        return f'Удаление "{self.get_object()}"'

    def delete(self, *args, **kwargs):
        response = super().delete(*args, **kwargs)

        if self.request.is_ajax():
            response = HttpResponse('ok')

        return response

core/views/admin.py
from django.conf import settings
from django.views.generic import TemplateView
from django.contrib.auth.mixins import PermissionRequiredMixin


class Management(PermissionRequiredMixin, TemplateView):
    template_name = 'core/admin.html'
    permission_required = 'core.view_management'

core/templates/core/user/edit.html
{% extends 'core/base_edit.html' %}
{% load bootstrap4 %}
{% load static %}

{% block css %}
    {{ block.super }}
    <style>
        .form-check {
            margin-top: 20px;
        }
    </style>
{% endblock %}

{% block fields %}
    <legend>{% if object.id %}Редактирование пользователя "{{ object }}"{% else %}Создание нового пользователя{% endif %}</legend>
    <div class="row">
        <div class="col-sm-6 border-right">
            {% bootstrap_field form.username layout='horizontal' %}
            <div class="form-group row">
                <label class="col-md-3 col-form-label" for="id_username">Пароль</label>
                <div class="col-md-9">
                    <div class="input-group">
                        <input type='text' name="new_password" id="id_new_password" class="form-control" autocomplete="off"
                               value="" placeholder="Новый пароль">
                        <span class="input-group-append">
                            <button type="button" class="input-group-text btn btn-outline-secondary generate-password" data-toggle="tooltip" title="Сгенерировать пароль">
                                <i class="fa fa-key"></i>
                            </button>
                        </span>
                    </div>
                    <small class="form-text text-muted" style="list-style: none">{{ form.new_password.help_text|safe }}</small>
                </div>
            </div>
            {% bootstrap_field form.groups layout='horizontal' %}
            {% bootstrap_field form.is_active layout='horizontal' %}
            {% bootstrap_field form.is_superuser layout='horizontal' %}
        </div>
        <div class="col-sm-6">
            {% bootstrap_field form.last_name layout='horizontal' %}
            {% bootstrap_field form.first_name layout='horizontal' %}
            {% bootstrap_field form.email layout='horizontal' %}
            {% bootstrap_field form.orgs layout='horizontal' %}
            {% bootstrap_field form.post layout='horizontal' %}
            {% bootstrap_field form.document_types layout='horizontal' %}
        </div>
    </div>

    {% if can_send_email_user_credentials %}
        <!-- Modal -->
        <div class="modal fade" id="needSendPasswordEmailModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Отправить письмо с учетными данными (логин и пароль) на электронную почту пользователя?</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-success">
                            <i class="fa fa-save"></i> Сохранить без отправки
                        </button>
                        <button type="submit" class="btn btn-primary" name="send_email_user_credentials" value="1">
                            <i class="fa fa-send"></i> Сохранить и отправить
                        </button>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

{% endblock %}



{% block buttons %}
    <div class="row">
        <div class="col-6">
            {% if object.id %}
                <a href="./delete/" class="btn btn-danger">
                    <i class="fa fa-trash"></i> Удалить
                </a>
            {% endif %}
        </div>

        <div class="col-6 text-right">
            <button class="btn btn-success btn-save" type="button">
                <i class="fa fa-save"></i> Сохранить
            </button>
        </div>
    </div>
{% endblock %}

{% block js %}
    {{ block.super }}
    <script>
        let canSendUserCredentials = {{ can_send_email_user_credentials|yesno:'true, false' }}
    </script>
    <script src="{% static 'core/js/user/edit.js' %}"></script>
{% endblock %}

core/templates/core/user/list.html
{% extends 'core/base_list.html' %}
{% load bootstrap4 %}

{% block form %}
    <div class="row">
        <div class="col-sm-6">
            {% bootstrap_field form.username layout='horizontal' %}
            {% bootstrap_field form.last_name layout='horizontal' %}
        </div>
        <div class="col-sm-6">
            {% bootstrap_field form.is_active layout='horizontal'%}
        </div>
    </div>
{% endblock %}

{% block additional_btn %}
    <a href="{% url 'core:user_add' %}" class="btn btn-success">
        <i class="fa fa-plus"></i> Создать
    </a>
{% endblock %}

{% block table_head %}
    <th>№</th>
    <th>Логин</th>
    <th>Фамилия</th>
    <th>Имя</th>
    <th>Организации</th>
    <th>Активен</th>
{% endblock table_head %}

{% block table_body %}
    <td>{{ page_obj.start_index|default:1|add:forloop.counter0 }}</td>
    <td>
        <a href="{% url 'core:user_edit' object.id %}">{{ object.username }}</a>
    </td>
    <td>{{ object.last_name }}</td>
    <td>{{ object.first_name }}</td>
    <td>{{ object.core.get_orgs|join:', ' }}</td>
    <td>{{ object.is_active|yesno:'да, нет' }}</td>
{% endblock %}