background_tasks/urls.py
from django.urls import path
from rest_framework import routers

import background_tasks.views.task
import background_tasks.views.rest

app_name = 'background_task'

urlpatterns = [
    path('', background_tasks.views.task.Search.as_view(), name='task_search'),
    path('<int:pk>/', background_tasks.views.task.Detail.as_view(), name='task_info'),
    path('<int:pk>/cancel/', background_tasks.views.task.Cancel.as_view(), name='task_cancel'),
    path('<int:pk>/restart/', background_tasks.views.task.Restart.as_view(), name='task_restart'),
]


router = routers.DefaultRouter()
router.register('rest/task', background_tasks.views.rest.TaskViewSet)
urlpatterns += router.urls

core/urls.py
from django.urls import path

from core.views import index, login
from core.views import user
from core.views import worker
from core.views import reports
from core.views import directions
from core.views import log
from core.views import rest

app_name = 'core'

urlpatterns = [
    path('', index.Index.as_view(), name='index'),

    path('user/', user.Search.as_view(), name='user'),
    path('user/add/', user.Edit.as_view(), name='user_add'),
    path('user/<int:pk>/', user.Edit.as_view(), name='user_edit'),
    path('user/<int:pk>/delete/', user.Delete.as_view(), name='user_delete'),

    path('workers/', worker.Search.as_view(), name='workers'),
    path('reports/workers_done_report/', reports.WorkersDoneReport.as_view(), name='workers_done_report'),

    path('log/', log.Log.as_view(), name='log'),

    path('directions/', directions.Search.as_view(), name='direction_list'),
    path('directions/add/', directions.Edit.as_view(), name='direction_add'),
    path('directions/<int:number>/', directions.Edit.as_view(), name='direction_edit'),
    path('directions/<int:number>/delete/', directions.Delete.as_view(), name='direction_delete'),
    path('directions/<int:number>/print/', directions.Print.as_view(), name='direction_print'),

    path('rest/orgs/', rest.Orgs.as_view(), name='rest_orgs'),
    path('rest/workers/', rest.Workers.as_view(), name='rest_workers'),
    path('rest/documents/choices/', rest.DocumentsChoices.as_view(), name='rest_documents_choices'),
    path('rest/documents/print/', rest.DocumentPrint.as_view(), name='rest_documents_print'),
    path('rest/worker_documents/', rest.WorkerDocuments.as_view(), name='rest_worker_documents'),
    path('rest/law_items/', rest.LawItems.as_view(), name='rest_law_items'),
    path('rest/generate_password/', rest.GeneratePasswordView.as_view(), name='rest_generate_password'),

    path('password_change_required/', login.PasswordChangeRequired.as_view(), name='password_change_required'),
    path('password_forgot/', login.PasswordForgot.as_view(), name='password_forgot'),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, PasswordChangeView, logout_then_login
from django.views.generic import TemplateView

import core.urls
import help.urls
import background_tasks.urls
from core.views.login import Login

urlpatterns = [
    path('', include(core.urls, namespace='core')),
    path('help/', include(help.urls, namespace='help')),
    path('background_tasks/', include(background_tasks.urls, namespace='background_tasks')),
    path('admin/', admin.site.urls),

    path('login/', Login.as_view(), name='login'),
    path('logout/', logout_then_login, {'login_url': '/login/?next=/'}, name='logout'),

    path('password_change/', PasswordChangeView.as_view(template_name='core/password_change.html',
                                                        success_url='/logout/'), name='password_change'),
]

handler403 = 'core.views.response_forbidden_handler'
handler404 = 'core.views.response_not_found_error_handler'
handler500 = 'core.views.response_server_error_handler'

if settings.DEBUG:
    urlpatterns += static('node_modules', document_root=settings.BASE_DIR + '/node_modules')
    urlpatterns += static('media', document_root=settings.MEDIA_ROOT)

    urlpatterns = [
        # для отладки страниц ошибок
        path('403/', TemplateView.as_view(template_name='core/errors/403.html')),
        path('404/', TemplateView.as_view(template_name='core/errors/404.html')),
        path('500/', TemplateView.as_view(template_name='core/errors/500.html')),
    ] + urlpatterns

background_tasks/models.py
import os
import pickle
import tempfile
from typing import Callable, Dict
import importlib

from django.conf import settings
from django.contrib.auth import get_user_model
from django.core.files import File
from django.core.validators import MaxValueValidator
from django.db import models
import core.models
from background_tasks import consts

User = get_user_model()


class Task(models.Model):
    name = models.CharField('Название задачи', max_length=255)
    description = models.TextField('Описание задачи', blank=True)
    user = models.ForeignKey(User, verbose_name='Пользователь', null=True, blank=True,
                             related_name='background_tasks', help_text='Пользователь, создавший задачу',
                             on_delete=models.PROTECT)

    func_path = models.CharField('Функция для вызова', max_length=255)
    params = models.FileField('Параметры', null=True, blank=True,
                              upload_to=lambda t, f_name: 'background_tasks/params_pickle/%s/%s' % (t.id, f_name),
                              help_text='Параметры, сериализованные в формате pickle')

    status = models.CharField('Статус выполнения задачи', choices=consts.STATUS_CHOICES,
                              default=consts.STATUS_PENDING, max_length=255, db_index=True)
    percent = models.PositiveSmallIntegerField('Процент выполнения', default=0, validators=[MaxValueValidator(100)])

    created_dt = models.DateTimeField('Создана', auto_now_add=True)
    start_dt = models.DateTimeField('Время начала выполнения задачи', null=True, blank=True)
    finish_dt = models.DateTimeField('Время окончания выполнения задачи', null=True, blank=True)

    result_attachment = models.FileField('Результат', null=True, blank=True,
                                         upload_to=lambda t, f_name: 'background_tasks/results/%s/%s' % (t.id, f_name))

    class Meta:
        verbose_name = 'Фоновая задача'
        verbose_name_plural = 'Фоновые задачи'
        ordering = ('-created_dt', )

    @classmethod
    def create_task(cls, method: Callable, name: str, user: 'core.models.DjangoUser', params: Dict,
                    description: str = '') -> 'Task':
        from background_tasks.tasks import start_task

        func_path = f"{method.__self__.__module__}.{method.__self__.__qualname__}.{method.__name__}"
        task = cls.objects.create(
            name=name,
            description=description,
            user=user,
            func_path=func_path
        )

        task.save_params(params)
        start_task.delay(task.id)

        return task

    @staticmethod
    def pickle_params(params: dict) -> str:
        """Сериализует параметры и возвращает путь к файлу с сериализованными данными"""
        if not os.path.exists(settings.DIR_FOR_TMP_FILES):
            os.makedirs(settings.DIR_FOR_TMP_FILES)

        pickled_path = tempfile.mkdtemp(dir=settings.DIR_FOR_TMP_FILES) + '/data.pickle'

        with open(pickled_path, 'wb') as f:
            pickle.dump(params, f)

        return pickled_path

    def save_params(self, params: dict):
        pickled_params_path = self.pickle_params(params)
        with open(pickled_params_path, 'rb') as f:
            self.params.save(name='params.pickle', content=File(f))
        os.unlink(pickled_params_path)

    def __str__(self):
        return self.name

    def get_func(self) -> Callable:
        try:
            # функция в пакете
            module_path = '.'.join(i for i in self.func_path.split('.')[:-1])
            func_name = self.func_path.split('.')[-1]
            module = importlib.import_module(module_path)
            return getattr(module, func_name)
        except ImportError:
            # метод класса
            module_path = '.'.join(i for i in self.func_path.split('.')[:-2])
            class_name = self.func_path.split('.')[-2]
            func_name = self.func_path.split('.')[-1]
            module = importlib.import_module(module_path)
            class_obj = getattr(module, class_name)
            return getattr(class_obj, func_name)

    def get_params(self) -> dict:
        if self.params:
            with open(self.params.path, 'rb') as f:
                return pickle.load(self.params)
        else:
            return {}

    def is_success(self) -> bool:
        return self.finish_dt and self.status == consts.STATUS_COMPLETE

    def is_fail(self) -> bool:
        return self.status == consts.STATUS_FAIL

    def in_progress(self) -> bool:
        return self.status == consts.STATUS_IN_PROCESS


class Log(models.Model):
    task = models.ForeignKey(Task, related_name='logs', on_delete=models.CASCADE)
    description = models.TextField('Описание')
    status = models.CharField('Статус выполнения задачи', choices=consts.STATUS_CHOICES,
                              default=consts.STATUS_IN_PROCESS, max_length=255, db_index=True)
    dc = models.DateTimeField('Создана', auto_now_add=True)

    class Meta:
        verbose_name = 'Запись журнала выполнения задачи'
        verbose_name_plural = 'Журнал выполнения задачи'
        ordering = ('-dc', )

    def is_success(self) -> bool:
        return self.status == consts.STATUS_COMPLETE

    def is_fail(self) -> bool:
        return self.status == consts.STATUS_FAIL

background_tasks/forms.py
from django import forms
import core.forms
import core.models
from background_tasks import consts


class TaskSearch(forms.Form):
    STATUS_CHOICES = [('', '')] + list(consts.STATUS_CHOICES)

    name = forms.CharField(label='Название', required=False)
    user = forms.ModelChoiceField(label='Пользователи', required=False,
                                  queryset=core.models.User.objects.filter(django_user__background_tasks__isnull=False).distinct(),
                                  widget=forms.Select(attrs={'class': 'need-select2'}))
    created_from = core.forms.RusDateField(label='Создана с', initial=None, required=False)
    created_to = core.forms.RusDateField(label='Создана по', initial=None, required=False)
    status = forms.ChoiceField(label='Статус', required=False, choices=STATUS_CHOICES)

    def clean_user(self):
        user = self.cleaned_data.get('user')
        if user:
            return user.django_user.id

background_tasks/views/rest.py
from rest_framework import viewsets
from rest_framework.authentication import SessionAuthentication
from rest_framework.permissions import IsAuthenticated
from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework import status

from background_tasks import models
from background_tasks import filters
from background_tasks import serializers
from background_tasks import datatools


class TaskViewSet(viewsets.ReadOnlyModelViewSet):
    authentication_classes = (SessionAuthentication, )
    permission_classes = (IsAuthenticated, )
    queryset = models.Task.objects.all()
    filter_class = filters.Task
    serializer_class = serializers.Task

    @action(detail=True, methods=['put'])
    def cancel(self, request, pk):
        task = models.Task.objects.get(id=pk)
        if not request.user.is_superuser and task.user != request.user:
            return Response(status=status.HTTP_404_NOT_FOUND)

        datatools.cancel_task(task)
        return Response(status=status.HTTP_200_OK)

    @action(detail=True, methods=['put'])
    def restart(self, request, pk):
        task = models.Task.objects.get(id=pk)
        if not request.user.is_superuser and task.user != request.user:
            return Response(status=status.HTTP_404_NOT_FOUND)

        datatools.restart_task(task)
        return Response(status=status.HTTP_200_OK)

background_tasks/views/task.py
from django.http import Http404, HttpResponse

import logging

from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import DetailView
from django.views.generic.edit import UpdateView

import core.generic.views
import core.generic.mixins

from background_tasks import models
from background_tasks import forms
from background_tasks import filters
from background_tasks import datatools

logger = logging.getLogger('db')


class Search(core.generic.mixins.FormMixin, core.generic.views.ListView):
    title = 'Фоновые задачи'
    template_name = 'background_tasks/task/search.html'
    model = models.Task
    form_class = forms.TaskSearch
    filter_class = filters.Task
    paginate_by = 20

    def get_queryset(self):
        qs = super().get_queryset()

        if not self.request.user.is_superuser:
            qs = qs.filter(user=self.request.user)

        return qs.order_by('-created_dt')


class Detail(DetailView):
    template_name = 'background_tasks/task/detail.html'
    model = models.Task

    # def get_object(self):
    #     return models.Task.objects.get(pk=self.kwargs['pk'])

    def get_title(self):
        return str(self.get_object())

    def get_success_url(self):
        return self.request.GET.get('next') or reverse('background_tasks:task_search')

    # def get_context_data(self, **kwargs):
    #     c = super().get_context_data(**kwargs)
    #     c['object'] = self.get_object()
    #     return c


class Cancel(UpdateView):
    model = models.Task

    def get_object(self, queryset=None):
        obj = super().get_object(queryset=queryset)
        if not self.request.user.is_superuser and obj.user != self.request.user:
            raise Http404()
        return obj

    def post(self, request, *args, **kwargs):
        task = self.get_object()
        datatools.cancel_task(task)
        if request.is_ajax():
            return HttpResponse('ok')
        else:
            return redirect(self.get_success_url())

    def get_success_url(self):
        return self.request.GET.get('next') \
               or reverse('background_tasks:task_info', kwargs={'pk': self.get_object().id})


class Restart(UpdateView):
    model = models.Task

    def get_object(self, queryset=None):
        obj = super().get_object(queryset=queryset)
        if not self.request.user.is_superuser and obj.user != self.request.user:
            raise Http404()
        return obj

    def post(self, request, *args, **kwargs):
        task = self.get_object()
        datatools.restart_task(task)
        if request.is_ajax():
            return HttpResponse('ok')
        else:
            return redirect(self.get_success_url())

    def get_success_url(self):
        return self.request.GET.get('next') \
               or reverse('background_tasks:task_info', kwargs={'pk': self.get_object().id})

background_tasks/templates/background_tasks/task/detail.html
{% extends BASE_TEMPLATE %}
{% load bootstrap4 %}
{% load static %}
{% load custom_tags %}

{% block css %}
    {{ block.super }}
    <style>
        input[type='checkbox'] {
            display: none;
        }

        .collapsible-content {
            display: none;
            overflow: hidden;
            transition: max-height .25s ease-in-out;
        }

        .toggle:checked + .lbl-toggle + .collapsible-content {
            display: block;
        }
    </style>
{% endblock %}


{% block container %}
    <p class="row">
        <span class="col-sm-2 text-right"><strong>Название </strong></span>
        <span class="col-sm-10">{{ object.name }}</span>
    </p>

    <p class="row">
        <span class="col-sm-2 text-right"><strong>Описание</strong></span>
        <span class="col-sm-10">{{ object.description }}</span>
    </p>


    {% if request.user.is_superuser %}
        <p class="row">
            <span class="col-sm-2 text-right"><strong>Пользователь</strong></span>
            <span class="col-sm-10">{{ object.user.core|default:'' }}</span>
        </p>

        <p class="row">
            <span class="col-sm-2 text-right"><strong>Функция для вызова</strong></span>
            <span class="col-sm-10">{{ object.func_path }}</span>
        </p>

        <div class="row">
            <div class="col-sm-2 text-right"><strong>Параметры</strong></div>
            <div class="col-sm-10">
                {% if object.params %}
                    <a href="{{ object.params.url }}">{{ object.params.name }}</a>

                    <input id="collapsible" class="toggle" type="checkbox">
                    <label for="collapsible" class="lbl-toggle btn btn-outline-secondary btn-sm">
                        <i class="fa fa-eye"></i>
                        Показать параметры
                    </label>
                    <div class="collapsible-content">
                        <div class="content-inner">
                            <pre>{{ object.get_params|pretty_value }}</pre>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
    {% endif %}

    <p class="row">
        <span class="col-sm-2 text-right"><strong>Статус выполнения</strong></span>
        <span class="col-sm-10 task-status">{{ object.status }}</span>
    </p>

    <p class="row">
        <span class="col-sm-2 text-right"><strong>Создана</strong></span>
        <span class="col-sm-10">{{ object.created_dt|default:'' }}</span>
    </p>

    <p class="row">
        <span class="col-sm-2 text-right"><strong>Время начала выполнения задачи</strong></span>
        <span class="col-sm-10 start-dt">{{ object.start_dt|default:'' }}</span>
    </p>

    <p class="row">
        <span class="col-sm-2 text-right"><strong>Время окончания выполнения задачи</strong></span>
        <span class="col-sm-10 finish-dt">{{ object.finish_dt|default:'' }}</span>
    </p>


    <div class="row">
        <div class="col-sm-12">
            <div class="progress" style="{% if not object.in_progress %}display: none{% endif %}">
                <div class="progress-bar" role="progressbar" aria-valuenow="{{ object.percent }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ object.percent }}%;">
                    {{ object.percent }}%
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-2">
            <form method="post" action="{% url 'background_tasks:task_cancel' object.id %}">
                {% csrf_token %}
                <button type="submit" name="cancel" class="btn btn-danger btn-block"
                    {% if object.start_dt %}disabled{% endif %}>
                    <i class="fa fa-remove"></i>
                    Отменить
                </button>
            </form>
        </div>

        <div class="col-sm-2">
            <form method="post" action="{% url 'background_tasks:task_restart' object.id %}">
                {% csrf_token %}
                <button type="submit" name="restart" class="btn btn-outline-secondary btn-block"
                        {% if object.in_progress %}disabled{% endif %}
                        data-toggle="tooltip" title="Перезапустить задачу">
                    <i class="fa fa-refresh"></i>
                    Пересоздать
                </button>
            </form>
        </div>

        <div class="col-sm-4"></div>
        <div class="col-sm-4">
            <a {% if object.result_attachment %}href="{{ object.result_attachment.url }}"{% endif %}
               style="{% if not object.result_attachment %}display: none{% endif %}"
               data-toggle="tooltip" title="Скачать результат выполнения задачи" target="_blank"
               class="btn btn-outline-secondary btn-block result-attachment"
                >
                <i class="fa fa-download"></i>
                Скачать
            </a>
        </div>
    </div>

    <hr>
    <div class="row">
        <h4>Журнал событий</h4>
        <table id="logs" class="table table-condensed table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Описание</th>
                    <th>Время</th>
                </tr>
            </thead>

            <tbody>
                {% for log in object.logs.all %}
                <tr class="{% if log.is_success %}badge-info
                           {% elif log.is_fail %}badge-danger
                           {% endif %}">
                    <td>{{ forloop.revcounter }}</td>
                    <td>{{ log.description }}</td>
                    <td>{{ log.dc }}</td>
                </tr>
                {% endfor %}
            </tbody>

        </table>
    </div>


{% endblock %}


{% block js %}
    {{ block.super }}
    <script>
        let taskId = {{ object.id }};
    </script>
    <script src="{% static "background_tasks/js/task/detail.js" %}"></script>
{% endblock %}

background_tasks/templates/background_tasks/task/search.html
{% extends 'core/base_list.html' %}
{% load bootstrap4 %}
{% load static %}

{% block form %}
    {% bootstrap_form_errors form %}

    <div class="row">
        {% for field in form %}
            <div class="col-md-6">{% bootstrap_field field layout='horizontal' %}</div>
        {% endfor %}
    </div>

{% endblock form %}


{% block pre_table %}
    {% if page_obj or object_list %}
        <span class="label label-info">Всего: {% if page_obj %}{{ page_obj.paginator.count }}{% else %}{{ object_list|length }}{% endif %}</span>
    {% endif %}
    {% csrf_token %}
{% endblock %}


{% block table_head %}
    <th>#</th>
    <th>Название</th>
    {% if request.user.is_superuser %}
        <th>Пользователь</th>
        <th>Функция</th>
    {% endif %}
    <th>Статус</th>
    <th></th>
    <th>Создана</th>
    <th>Началась</th>
    <th>Завершена</th>
    <th></th>
    <th></th>
{% endblock %}


{% block tbody %}
    {% for object in page_obj|default:object_list %}
        <tr id="task_{{ object.id }}" data-task-id="{{ object.id }}"
            class="{% if object.is_success %}success
                   {% elif object.is_fail %}danger
                   {% endif %}">
            <td>{{ forloop.counter }}</td>
            <td>
                <a href="{% url 'background_tasks:task_info' object.id %}?next={{ request.get_full_path|urlencode }}">
                    {{ object.name }}
                </a>
            </td>

            {% if request.user.is_superuser %}
                <td>{{ object.user.core|default:'' }}</td>
                <td title="{{ object.func_path }}">
                    {{ object.func_path|truncatechars:20 }}
                </td>
            {% endif %}

            <td>
                <div class="progress" style="{% if not object.in_progress %}display: none{% endif %}">
                    <div class="progress-bar" role="progressbar" aria-valuenow="{{ object.percent }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ object.percent }}%;">
                        {{ object.percent }}%
                    </div>
                </div>
                <span class="task-status" style="{% if object.in_progress %}display: none{% endif %}">{{ object.status }}</span>
            </td>
            <td>
                <span class="result-attachment-container" style="{% if not object.result_attachment %}display: none{% endif %}">
                    <a {% if object.result_attachment %}href="{{ object.result_attachment.url }}"{% endif %}
                       data-toggle="tooltip" title="Скачать результат выполнения задачи" target="_blank"
                       class="btn btn-outline-secondary btn-xs result-attachment"
                        >
                        <i class="fa fa-download"></i>
                    </a>
                </span>
            </td>
            <td>{{ object.created_dt }}</td>
            <td class="start-dt">{{ object.start_dt|default:'' }}</td>
            <td class="finish-dt">{{ object.finish_dt|default:'' }}</td>
            <td>
                <button type="button" name="cancel" value="{{ object.id }}" class="btn btn-danger btn-xs"
                        {% if object.start_dt %}disabled{% endif %}
                        data-toggle="tooltip" title="Отменить">
                    <i class="fa fa-remove"></i>
                </button>
            </td>
            <td>
                <button type="button" name="restart" value="{{ object.id }}" class="btn btn-outline-secondary btn-xs"
                        {% if object.in_progress %}disabled{% endif %}
                        data-toggle="tooltip" title="Перезапустить задачу">
                    <i class="fa fa-refresh"></i>
                </button>
            </td>
    {% endfor %}
{% endblock %}


{% block js %}
    {{ block.super }}
    <script src="{% static "background_tasks/js/task/search.js" %}"></script>
{% endblock %}